# Generated by Django 4.0.4 on 2022-05-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='sec',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='sem',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ISE', 'ISE'), ('Civil', 'Civil'), ('ME', 'ME'), ('Aeronautical', 'Aeronautical'), ('ECE', 'ECE'), ('Aerospace', 'Aerospace')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Basic',
        ),
    ]
