# Generated by Django 4.0.4 on 2022-05-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_note_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_file',
            field=models.FileField(blank=True, null=True, upload_to='notes_file/'),
        ),
    ]
