# Generated by Django 4.0.4 on 2022-05-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_note_note_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousYearQuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ISE', 'ISE'), ('Civil', 'Civil'), ('ME', 'ME'), ('Aeronautical', 'Aeronautical'), ('ECE', 'ECE'), ('Aerospace', 'Aerospace')], max_length=200, null=True)),
                ('sem', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True)),
                ('sec', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=200, null=True)),
                ('paper', models.FileField(blank=True, null=True, upload_to='prev_ques/')),
                ('ans', models.FileField(blank=True, null=True, upload_to='prev_ques/')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ISE', 'ISE'), ('Civil', 'Civil'), ('ME', 'ME'), ('Aeronautical', 'Aeronautical'), ('ECE', 'ECE'), ('Aerospace', 'Aerospace')], max_length=200, null=True)),
                ('sem', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True)),
                ('sec', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=200, null=True)),
                ('tut_ques', models.FileField(blank=True, null=True, upload_to='tutorials/')),
                ('tut_ans', models.FileField(blank=True, null=True, upload_to='tutorials/')),
            ],
        ),
    ]
