# Generated by Django 4.0.4 on 2022-05-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_previousyearquestionpaper_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('bname', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('sem', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.branch')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='PreviousYearQuestionPaper',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
