# Generated by Django 4.0.4 on 2022-05-24 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_branch_subname_delete_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_ques', models.FileField(blank=True, null=True, upload_to='tutorials/')),
                ('tut_ans', models.FileField(blank=True, null=True, upload_to='tutorials/')),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.subname')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_file', models.FileField(blank=True, null=True, upload_to='notes_file/')),
                ('subname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.subname')),
            ],
        ),
    ]
