# Generated by Django 4.0.4 on 2022-05-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_tutorial_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='nname',
            field=models.CharField(blank=True, default='notes', max_length=200, null=True),
        ),
    ]
