# Generated by Django 4.0.4 on 2022-05-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_rename_basic_tutorial_subname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='name_tut_ans',
            field=models.CharField(blank=True, default='tut_ans', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='name_tut_ques',
            field=models.CharField(blank=True, default='tut', max_length=200, null=True),
        ),
    ]
